name: "Frenchio"
description: "Stremio addon for French private trackers (YGG, Sharewood, ABNormal, etc.)"
version: "1.0.1"
slug: "frenchio"
url: "https://github.com/djodjo02130/frenchio"
arch:
  - amd64
  - aarch64
  - armv7
init: false
homeassistant_api: false
host_network: true
ingress: true
ingress_port: 0
panel_icon: "mdi:movie-search"
panel_title: "Frenchio"
options:
  PORT: 7777
  QBITTORRENT_ENABLE: false
  QBITTORRENT_PORT: 8080
schema:
  PORT: port
  TMDB_API_KEY: password?
  ALLDEBRID_API_KEY: password?
  TORBOX_API_KEY: password?
  DEBRIDLINK_API_KEY: password?
  QBITTORRENT_ENABLE: bool
  QBITTORRENT_HOST: str?
  QBITTORRENT_PORT: port?
  QBITTORRENT_USERNAME: str?
  QBITTORRENT_PASSWORD: password?
ports:
  7777/tcp: 7777
ports_description:
  7777/tcp: "Frenchio Web Interface"
