name: "Frenchio"
description: "Stremio addon for French private trackers (YGG, Sharewood, ABNormal, etc.)"
version: "1.0.0"
slug: "frenchio"
url: "https://github.com/djodjo02130/frenchio"
arch:
  - amd64
  - aarch64
  - armv7
init: false
homeassistant_api: false
host_network: true
ingress: true
ingress_port: 7777
panel_icon: "mdi:movie-search"
panel_title: "Frenchio"
options:
  TMDB_API_KEY: ""
  ALLDEBRID_API_KEY: ""
  TORBOX_API_KEY: ""
  DEBRIDLINK_API_KEY: ""
  QBITTORRENT_ENABLE: true
  QBITTORRENT_HOST: ""
  QBITTORRENT_PORT: 8080
  QBITTORRENT_USERNAME: ""
  QBITTORRENT_PASSWORD: ""
schema:
  TMDB_API_KEY: str?
  ALLDEBRID_API_KEY: str?
  TORBOX_API_KEY: str?
  DEBRIDLINK_API_KEY: str?
  QBITTORRENT_ENABLE: bool
  QBITTORRENT_HOST: str?
  QBITTORRENT_PORT: port?
  QBITTORRENT_USERNAME: str?
  QBITTORRENT_PASSWORD: str?
ports:
  7777/tcp: 7777
ports_description:
  7777/tcp: "Frenchio Web Interface"
