name: "Frenchio"
description: "Stremio addon for French private trackers (YGG, Sharewood, ABNormal, etc.)"
version: "1.0.3"
slug: "frenchio"
url: "https://github.com/djodjo02130/frenchio"
arch:
  - amd64
  - aarch64
  - armv7
init: false
homeassistant_api: false
host_network: true
ingress: true
ingress_port: 0
panel_icon: "mdi:movie-search"
panel_title: "Frenchio"
options:
  PORT: 7777
  QBITTORRENT_ENABLE: true
  MANIFEST_TITLE_SUFFIX: ""
  MANIFEST_BLURB: ""
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: ""
schema:
  PORT: port
  QBITTORRENT_ENABLE: bool
  MANIFEST_TITLE_SUFFIX: str?
  MANIFEST_BLURB: str?
  HTTP_PROXY: str?
  HTTPS_PROXY: str?
  NO_PROXY: str?
ports:
  7777/tcp: 7777
ports_description:
  7777/tcp: "Frenchio Web Interface"
