name: "Frenchio"
description: "Stremio addon for French private trackers (YGG, Sharewood, ABNormal, etc.)"
version: "1.0.6"
slug: "frenchio"
url: "https://github.com/djodjo02130/frenchio"
arch:
  - amd64
  - aarch64
  - armv7
init: false
ingress: true
ingress_port: 7777
panel_icon: "mdi:movie-search"
panel_title: "Frenchio"
options:
  QBITTORRENT_ENABLE: true
  MANIFEST_TITLE_SUFFIX: ""
  MANIFEST_BLURB: ""
  HTTP_PROXY: ""
  HTTPS_PROXY: ""
  NO_PROXY: ""
schema:
  QBITTORRENT_ENABLE: bool
  MANIFEST_TITLE_SUFFIX: str?
  MANIFEST_BLURB: str?
  HTTP_PROXY: str?
  HTTPS_PROXY: str?
  NO_PROXY: str?
